@url = http://localhost:8080/api/employees
@employeeToken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzaGlmdC1zY2hlZHVsZXItYXBpIiwic3ViIjoic2FsbHlAam9uZXMuY29tIiwiYXV0aG9yaXRpZXMiOiJST0xFX0VNUExPWUVFIiwiYXBwVXNlcklkIjoyLCJleHAiOjE2NTY3MTg0ODh9.PMbiYYmrSIkMiuZVPHwUl-A-94SQ09qD0e4Iu0cBSys
@managerToken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzaGlmdC1zY2hlZHVsZXItYXBpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfTUFOQUdFUiIsImFwcFVzZXJJZCI6MSwiZXhwIjoxNjU2ODI1NDk0fQ.dnO4g55HucObd_iPPz-jfaahejfzftOAKoYbviNPqO0
### Employee token fetch

POST http://localhost:8080/api/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "sally@jones.com",
  "password": "P@ssw0rd!"
}


### Manager token fetch

POST http://localhost:8080/api/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "P@ssw0rd!"
}

### finduser by token
GET {{url}}/employee HTTP/1.1
Authorization: Bearer {{managerToken}}


### //findAll (should fail for employee)

GET {{url}} HTTP/1.1
Authorization: Bearer {{employeeToken}}

### findAll (should work for manager)

GET {{url}} HTTP/1.1
Authorization: Bearer {{managerToken}}

### //findById

GET {{url}}/2 HTTP/1.1
Authorization: Bearer {{managerToken}}

###

GET {{url}}/user/sally@jones.com
Authorization: Bearer {{managerToken}}

### create should not work for employee

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{employeeToken}}

{
  "employeeId": 6,
  "firstName": "Benny",
  "lastName": "Benson",
  "appUserId": 6,
  "wage": 0.0
}


### create should  work for manager

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{managerToken}}

{
  "firstName": "Benny",
  "lastName": "Benson",
  "appUserId": 6,
  "wage": 10
}

### update should not work for employee

PUT {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{employeeToken}}

{
  "employeeId": 1,
  "firstName": "John",
  "lastName": "Smith",
  "appUserId": 1,
  "wage": 10.0
}

### update should work for manager
PUT {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{managerToken}}

{
  "employeeId": 1,
  "firstName": "John",
  "lastName": "Smith",
  "appUserId": 1,
  "wage": 10.0
}

### delete should work for manager

DELETE {{url}}/5 HTTP/1.1
Authorization: Bearer {{managerToken}}

### delete should not work for employee

DELETE {{url}}/5 HTTP/1.1
Authorization: Bearer {{employeeToken}}

###