@url = http://localhost:8080/api/shifts
@managerToken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzaGlmdC1zY2hlZHVsZXItYXBpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfTUFOQUdFUiIsImFwcFVzZXJJZCI6MSwiZXhwIjoxNjU2ODIzMjU2fQ.hRa0ftisiD6855c-ZX4mGw1Qep9f8E4MEcVu-TffOIk
@employeeToken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzaGlmdC1zY2hlZHVsZXItYXBpIiwic3ViIjoic2FsbHlAam9uZXMuY29tIiwiYXV0aG9yaXRpZXMiOiJST0xFX0VNUExPWUVFIiwiYXBwVXNlcklkIjoyLCJleHAiOjE2NTY3NzQ2MjZ9.KScjbO7X7VGXqAsu3i1drSZXad3ebIrry0VVj4djSmM



### Manager token fetch

POST http://localhost:8080/api/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "P@ssw0rd!"
}

### Employee token fetch

POST http://localhost:8080/api/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "sally@jones.com",
  "password": "P@ssw0rd!"
}

### MANAGER

GET {{url}} HTTP/1.1
Authorization: Bearer {{managerToken}}

###

GET {{url}}/schedule/1/1 HTTP/1.1
Authorization: Bearer {{managerToken}}

###

GET {{url}}/1 HTTP/1.1 
Authorization: Bearer {{managerToken}}

###

GET {{url}}/user HTTP/1.1
Authorization: Bearer {{employeeToken}}

###

GET {{url}}/employee/1 HTTP/1.1 
Authorization: Bearer {{managerToken}}

###

GET {{url}}/user/john@smith.com HTTP/1.1 
Authorization: Bearer {{managerToken}}

###

GET {{url}}/user/sally@jones.com HTTP/1.1 
Authorization: Bearer {{employeeToken}}

###
GET {{url}}/user/arin@brown.com HTTP/1.1 
Authorization: Bearer {{managerToken}}

###
GET {{url}}/schedule/1 HTTP/1.1 
Authorization: Bearer {{managerToken}}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{managerToken}}

{
    "employeeId": 1,
    "startTime": "2020-02-02T09:00:00",
    "endTime": "2020-02-02T18:00:00",
    "scheduleId": 1,
    "earned": "a"
}

###

DELETE {{url}}/1 HTTP/1.1
Authorization: Bearer {{managerToken}}

###

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{managerToken}}

{
  "shiftId": 2,
  "scheduleId": 2,
  "employeeId": 2,
  "startTime": "2022-06-05T12:00:00",
  "endTime": "2022-06-05T16:00:00",
  "earned": "a"
}

### EMPLOYEE
### ALL BELOW SHOULD FAIL
DELETE {{url}}/1 HTTP/1.1
Authorization: Bearer {{employeeToken}}

###

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{employeeToken}}

{
  "shiftId": 2,
  "scheduleId": 2,
  "employeeId": 2,
  "startTime": "2022-06-05T12:00:00",
  "endTime": "2022-06-05T16:00:00",
  "earned": "a"
}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{employeeToken}}

{
    "employeeId": 1,
    "startTime": "2020-02-02T09:00:00",
    "endTime": "2020-02-02T18:00:00",
    "scheduleId": 1,
    "earned": "a"
}

### ALL BELOW SHOULD WORK

GET {{url}}/schedule/1 HTTP/1.1 
Authorization: Bearer {{employeeToken}}

###

GET {{url}}/user/john@smith.com HTTP/1.1 
Authorization: Bearer {{employeeToken}}

###

GET {{url}}/employee/1 HTTP/1.1 
Authorization: Bearer {{employeeToken}}

###